version: '2'
services:
  solr:
    image: solr:8
    ports:
      - 8983:8983
    volumes:
      - solrdata:/opt/solr/server/solr
      - ${PWD}/badbreaking:/opt/solr/server/solr/configsets/badbreaking # hack default to use our config
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate # run precreate to create our core with our mounted configset
#      - fut_solr

volumes:
  solrdata:


