version: '3'
services:
  solr:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - ${PWD}/conf:/opt/solr/server/solr/configsets/badbreaking/conf
    entrypoint:
      - bash
      - "-c"
      - "precreate-core testcore1 /opt/solr/server/solr/configsets/badbreaking; precreate-core testcore2 /opt/solr/server/solr/configsets/badbreaking; exec solr -f"
volumes:
  data: